[tool.poetry]
name = "grimoirelab-core"
version = "1.0.0-alpha.1"
description = "Core of GrimoireLab"
authors = [
    "GrimoireLab Developers"
]
license = "GPL-3.0+"

readme = "README.md"

homepage = "https://chaoss.github.io/grimoirelab/"
repository = "https://github.com/chaoss/grimoirelab-core"

keywords = [
    "development",
    "grimoirelab"
]

packages = [
    { include = "grimoirelab", from = "src" },
]

include = [
    { path = "grimoirelab/core/templates" },
    { path = "ui", format = "sdist" },
    { path = "AUTHORS", format = "sdist" },
    { path = "NEWS", format = "sdist" },
    { path = "README.md", format = "sdist" },
]

exclude = [
    "ui/tests",
    "ui/.storybook",
]

classifiers = [
   "Development Status :: 4 - Beta",
   "Intended Audience :: Developers",
   "Topic :: Software Development",
   "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
   "Programming Language :: Python :: 3"
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/chaoss/grimoirelab-core/issues"

[tool.poetry.scripts]
grimoirelab = "grimoirelab.core.runner.cmd:grimoirelab"

[tool.poetry.dependencies]
python = "^3.11"

django = "^5.2"
django-rq = "^3.1"
mysqlclient = "^2.0.3"
django-cors-headers = "^4.6.0"
djangorestframework = "^3.15.2"
opensearch-py = "^3.0.0"
djangorestframework-simplejwt = "^5.4.0"
django-storages = {version = "^1.14.6", extras = ["google"]}
drf-spectacular = "^0.28.0"
django-structlog = "^9.0.1"
structlog = "^25.2.0"
grimoirelab-toolkit = {version = ">=1.2.0", allow-prereleases = true}
perceval = {version = ">=1.3.4", allow-prereleases = true}
sortinghat = {version = ">=1.11.0", allow-prereleases = true}
grimoirelab-chronicler = {version = ">=0.0.1rc2", allow-prereleases = true}
granian = "^2.8.3"

[tool.poetry.group.dev.dependencies]
fakeredis = "^2.29.0"
httpretty = "^1.1.4"
pytest-django = "^4.11.1"
testcontainers = "^4.10.0"
ruff = "^0.12.3"
pre-commit = "^4.2.0"

[tool.poetry-prehook]
pre-install = [
    "python build/build-ui.py",
]
pre-build = [
    "python build/build-ui.py",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 100
exclude = [
    ".eggs",
    ".git",
    ".git-rewrite",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".vscode",
    "__pypackages__",
    "__pycache__",
    "_build",
    "build",
    "dist",
    "docs",
    "docker",
    "ui",
    "node_modules",
    "site-packages",
    "src/**/migrations/*.py",
]
